# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/red_sands/all/red_sands.rbi
#
# red_sands-0.1.0

module RedSands
end
module RedSands::Actions
end
module RedSands::Boards
end
module RedSands::Cards
end
module RedSands::Concerns
end
module RedSands::Rules
end
module RedSands::Troops
end
