# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `wisper-rspec` gem.
# Please instead update this file by running `bin/tapioca gem wisper-rspec`.

# source://wisper-rspec//lib/wisper/rspec/version.rb#1
module Wisper; end

# Prior to being extracted from Wisper the matcher was namespaced as Rspec,
# it is now RSpec. This will raise a helpful message for those upgrading to
# Wisper 2.0
#
# source://wisper-rspec//lib/wisper/rspec/version.rb#2
module Wisper::Rspec; end

# source://wisper-rspec//lib/wisper/rspec/version.rb#3
Wisper::Rspec::VERSION = T.let(T.unsafe(nil), String)
